600000ms th_a       db_block.cpp:218              _push_block          ] Failed to push new block:
10 assert_exception: Assert Exception
hi == 0:
    {}
    th_a  uint128.hpp:106 to_uint64

    {}
    th_a  db_maint.cpp:464 process_budget

    {"next_block.block_num()":36}
    th_a  db_block.cpp:591 _apply_block
600001ms th_a       witness.cpp:175               block_production_loo ] Got exception while generating block:
10 assert_exception: Assert Exception
hi == 0:
    {}
    th_a  uint128.hpp:106 to_uint64

    {}
    th_a  db_maint.cpp:464 process_budget
